# from python 3.10

FROM python:3.10-alpine

ARG TOKEN
ARG ATLAS_URI
ARG DB_NAME

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR .

COPY . .

RUN poetry install

CMD ["poetry", "run", "python", "src/main.py"]
